import { ThemeState, DarkColorPalette, LightColorPalette } from "../theme/color-palette.slint";

export component ContentPlaceHolder inherits Rectangle {
    
    background: transparent;

    VerticalLayout {
        alignment: center;

        spacing: 10px;

        Text {
            horizontal-alignment: center;

            text: "Nothing here!";
            color: ThemeState.isLight ? LightColorPalette.Text : DarkColorPalette.Text;
            font-size: 36px;
        }
        Text {
            horizontal-alignment: center;

            text: "Add a lesson to get started.";
            color: ThemeState.isLight ? LightColorPalette.TextLight : DarkColorPalette.TextLight;
            font-size: 16px;
        }
    }
}