import { ThemeState, DarkColorPalette, LightColorPalette } from "../theme/color-palette.slint";

export component EmptyState inherits Rectangle {
    in-out property <string> main_text;
    in-out property <string> tip_text;
    
    background: transparent;

    VerticalLayout {
        alignment: center;

        spacing: 10px;

        Text {
            horizontal-alignment: center;

            text: main_text;
            color: ThemeState.isLight ? LightColorPalette.Text : DarkColorPalette.Text;
            font-size: 36px;
        }
        Text {
            horizontal-alignment: center;

            text: tip_text;
            color: ThemeState.isLight ? LightColorPalette.TextLight : DarkColorPalette.TextLight;
            font-size: 16px;
        }
    }
}