import { EmptyState } from "empty-state.slint";
import { Button, LineEdit, ListView } from "std-widgets.slint";
import { ThemeState, DarkColorPalette, LightColorPalette } from "../theme/color-palette.slint";
import { LessonData } from "../models.slint";
import { LessonCard } from "../components/lesson-card.slint";

export component LessonsPage inherits Rectangle {
    // Properties
    in-out property <string> topic;
    in-out property <string> new_lesson_text: "";
    in-out property <[LessonData]> lessons: [];

    // Callbacks
    callback add_lesson(string);
    callback load_lessons_requested();

    background: transparent;

    VerticalLayout {
        HorizontalLayout {
            padding: 10px;
            spacing: 10px;

            Text {
                vertical-alignment: center;
                height: 30px;

                text: topic;
                font-size: 20px;

                color: ThemeState.isLight ? LightColorPalette.Text : DarkColorPalette.Text;
            }

            LineEdit {
                placeholder-text: "New lesson name..";
                font-size: 16px;

                text <=> root.new_lesson_text;

                accepted() => {
                    add_lesson(root.new_lesson_text);
                    root.new_lesson_text = "";
                }
            }

            Button {
                text: "+ Add lesson";

                clicked => {
                    add_lesson(root.new_lesson_text);
                    root.new_lesson_text = "";
                }
            }
        }

        VerticalLayout {
            padding: 10px;

            if lessons.length == 0 : EmptyState {
                main_text: "Nothing here!";
                tip_text: "Create a lesson to get started.";
            }

            if lessons.length != 0 : ListView {
                for lesson in lessons : Rectangle {
                    height: 110px;
                    width: parent.width - 10px;

                    LessonCard {
                        width: parent.width - 10px;
                        x: 0px;
                        y: 10px;

                        name: lesson.name;
                        last_reviewed: "Blank";
                        next_review: lesson.next_review;
                        stage: "Blank";
                        duration: "Blank";
                    }
                }
            }
        }
    }
}