import { EmptyState } from "empty-state.slint";
import { Button, LineEdit, ListView } from "std-widgets.slint";
import { ThemeState, DarkColorPalette, LightColorPalette } from "../theme/color-palette.slint";

export component LessonsPage inherits Rectangle {
    // Properties
    in-out property <string> topic;
    in-out property <string> new_lesson_text: "";

    // Callbacks
    callback add_lesson(string);

    background: transparent;

    VerticalLayout {
        HorizontalLayout {
            padding: 10px;
            spacing: 10px;

            Text {
                vertical-alignment: center;
                height: 30px;

                text: topic;
                font-size: 20px;

                color: ThemeState.isLight ? LightColorPalette.Text : DarkColorPalette.Text;
            }

            LineEdit {
                placeholder-text: "New lesson name..";
                font-size: 16px;

                text <=> root.new_lesson_text;

                accepted() => {
                    add_lesson(root.new_lesson_text);
                    root.new_lesson_text = "";
                }
            }

            Button {
                text: "+ Add lesson";

                clicked => {
                    add_lesson(root.new_lesson_text);
                    root.new_lesson_text = "";
                }
            }
        }

        EmptyState {
            main_text: "Nothing here!";
            tip_text: "Create a lesson to get started.";
        }
    }
}