import { ThemeState, DarkColorPalette, LightColorPalette } from "../theme/color-palette.slint";
import { VerticalBox } from "std-widgets.slint";
import { Button } from "button.slint";

export component LessonCard inherits Rectangle {
    // Properties
    in-out property <string> name;
    in-out property <string> last_reviewed;
    in-out property <string> next_review;
    in-out property <string> stage;
    in-out property <int> due;

    // Callbacks
    callback review_button_pressed();
    callback delete_requested();
    callback edit_requested();

    height: 100px;

    border-color: ThemeState.isLight ? LightColorPalette.Border : DarkColorPalette.Border;
    border-radius: 10px;

    background: ThemeState.isLight ? LightColorPalette.SideBar : DarkColorPalette.SideBar;

    HorizontalLayout {
        padding: 10px;
        spacing: 5px;

        VerticalLayout {
            horizontal-stretch: 1;
            padding: 5px;

            Text {
                text: root.name;
                color: ThemeState.isLight ? LightColorPalette.Text : DarkColorPalette.Text;
                font-size: 20px;
            }
            Text {
                text: "Last reviewed: " + root.last_reviewed;
                color: ThemeState.isLight ? LightColorPalette.TextLight : DarkColorPalette.TextLight;
                font-size: 14px;
            }
            Text {
                text: "Next review: " + root.next_review;
                color: ThemeState.isLight ? LightColorPalette.TextLight : DarkColorPalette.TextLight;
                font-size: 14px;
            }
            Text {
                text: root.stage + " · " + ((root.due <= 0) ? "today" : @tr("{} days.", root.due));
                color: ThemeState.isLight ? LightColorPalette.SelectedText : DarkColorPalette.SelectedText;
                font-size: 12px;
            }
        }

        VerticalLayout {
            alignment: center;

            Button {
                height: 65px;
                text: "Review";

                icon: @image-url("../../assets/icons/done.svg");
                colorize-icon: true;

                enabled: due <= 0;

                clicked => {
                    root.review_button_pressed()
                }
            }
        }

        VerticalLayout {
            alignment: center;
            spacing: 5px;

            Button {
                height: 30px;
                text: "Edit";

                icon: @image-url("../../assets/icons/edit.svg");
                icon-size: 16px;
                colorize-icon: true;

                clicked => {
                    root.edit_requested();
                }
            }

            Button {
                height: 30px;
                text: "Delete";

                icon: @image-url("../../assets/icons/delete.svg");
                icon-size: 16px;
                colorize-icon: true;

                clicked => {
                    root.delete_requested();
                }
            }
        }
    }
}