import { ThemeState, LightColorPalette, DarkColorPalette } from "../theme/color-palette.slint";
export component SettingsSection inherits Rectangle {
    height: self.preferred-height;

    background: ThemeState.isLight ? LightColorPalette.SideBar : DarkColorPalette.SideBar;

    border-radius: 10px;
    border-color: ThemeState.isLight ? LightColorPalette.Border : DarkColorPalette.Border;
    border-width: 1px;
}

export component Setting inherits Rectangle {
    height: 40px;
}