import { ThemeState, DarkColorPalette, LightColorPalette } from "../theme/color-palette.slint";
import { Button, HorizontalBox } from "std-widgets.slint";

export component TopicCard inherits Rectangle {
    in-out property <bool> isSelected: false;
    in-out property <string> title;
    in-out property <int> lessons;
    in-out property <int> due;

    callback delete_requested();
    callback selected();
    
    height: 60px;
    
    area:= TouchArea {
        height: parent.height;
        width: parent.width;

        clicked => {
            selected();
        }
    }

    background: ThemeState.isLight ? (isSelected ? LightColorPalette.Selected : (area.has-hover ? LightColorPalette.Hover : transparent)) : (isSelected? DarkColorPalette.Selected : (area.has-hover ? DarkColorPalette.Hover : transparent));
    animate background {
         duration: 80ms;
    }
    
    border-radius: 10px;

    HorizontalLayout {
        padding: 10px;

        VerticalLayout {
            Text {
                text: title;
                font-size: 18px;
                color: ThemeState.isLight ? (isSelected ? LightColorPalette.SelectedText : LightColorPalette.Text) : (isSelected ? DarkColorPalette.SelectedText : DarkColorPalette.Text);
            }

            Text {
                text: lessons + " lessons · " + due + " due";
                font-size: 14px;
                color: ThemeState.isLight ? LightColorPalette.TextLight : DarkColorPalette.TextLight;
            }
        }

        // Spacer
        Rectangle {

        }

        VerticalLayout {
            alignment: center;

            Button {
                text: "X";
                height: 35px;
                width: 35px;

                clicked => {
                    delete_requested();
                }
            }
        }
    }
}