import { ThemeState, DarkColorPalette, LightColorPalette } from "../theme/color-palette.slint";
import { HorizontalBox } from "std-widgets.slint";
import { IconButton } from "icon-button.slint";

export component TopicCard inherits Rectangle {
    height: 60px;
    
    // Properties
    in-out property <bool> isSelected: false;
    in-out property <string> title;
    in-out property <int> lessons;
    in-out property <int> due;

    // Callbacks
    callback delete_requested();
    callback edit_requested();
    callback selected();

    area:= TouchArea {
        height: parent.height;
        width: parent.width;

        clicked => {
            selected();
        }
    }

    background: ThemeState.isLight ? (isSelected ? LightColorPalette.Selected : (area.has-hover ? LightColorPalette.Hover : transparent)) : (isSelected? DarkColorPalette.Selected : (area.has-hover ? DarkColorPalette.Hover : transparent));
    animate background {
         duration: 80ms;
    }
    
    border-radius: 10px;

    HorizontalLayout {
        padding: 10px;
        spacing: 5px;

        VerticalLayout {
            Text {
                text: title;
                font-size: 18px;
                color: ThemeState.isLight ? (isSelected ? LightColorPalette.SelectedText : LightColorPalette.Text) : (isSelected ? DarkColorPalette.SelectedText : DarkColorPalette.Text);
            }

            Text {
                text: lessons + " lessons · " + due + " due";
                font-size: 14px;
                color: ThemeState.isLight ? LightColorPalette.TextLight : DarkColorPalette.TextLight;
            }
        }

        // Spacer
        Rectangle {

        }

        VerticalLayout {
            alignment: center;

            IconButton {
                height: 30px;
                width: 30px;

                icon: @image-url("../../assets/icons/edit.svg");

                clicked => {
                    edit_requested();
                }
            }
        }

        VerticalLayout {
            alignment: center;

            IconButton {
                height: 30px;
                width: 30px;

                icon: @image-url("../../assets/icons/delete.svg");

                clicked => {
                    delete_requested();
                }
            }
        }
    }
}