export global ThemeState {
    in-out property <bool> isLight: false;
}

export global LightColorPalette {
    in-out property <color> Background: #ffffff;
    in-out property <color> SideBar: #f5f2f0;
    in-out property <color> Border: #00000014;
    in-out property <color> Text: #141413;
    in-out property <color> TextLight: #6b6b68;
    in-out property <color> Selected: #e6f1fb;
    in-out property <color> SelectedText: #185fa5;
    in-out property <color> Hover: #f0efe9;
    in-out property <color> DueBackground: #faeeda;
    in-out property <color> DueText: #854f0b;
}

export global DarkColorPalette {
    in-out property <color> Background: #3d3d3a;
    in-out property <color> SideBar: #2b2b29;
    in-out property <color> Border: #ffffff40;
    in-out property <color> Text: #f5f4f0;
    in-out property <color> TextLight: #b5b4af;
    in-out property <color> Selected: #0c447c;
    in-out property <color> SelectedText: #b5d4f4;
    in-out property <color> Hover: #38382f;
    in-out property <color> DueBackground: #633806;
    in-out property <color> DueText: #fac775;
}