export global LightColorPalette {
    in-out property <color> White: #ffffff;
    in-out property <color> Cream: #f5f2f0;
    in-out property <color> Hairline: #00000014;
    in-out property <color> Ink: #141413;
    in-out property <color> Slate: #6b6b68;
    in-out property <color> Sky: #e6f1fb;
    in-out property <color> Ocean: #185fa5;
    in-out property <color> Sand: #faeeda;
    in-out property <color> Amber: #854f0b;
    in-out property <color> Marigold: #ef9f27;
}

export global DarkColorPalette {
    in-out property <color> Charcoal: #3d3d3a;
    in-out property <color> Onyx: #2b2b29;
    in-out property <color> HairlineDark: #ffffff14;
    in-out property <color> Fog: #f5f4f0;
    in-out property <color> Ash: #b5b4af;
    in-out property <color> Midnight: #0c447c;
    in-out property <color> Powder: #b5d4f4;
    in-out property <color> Umber: #633806;
    in-out property <color> Honey: #fac775;
    in-out property <color> MarigoldDark: #ba7517;
}