import { LineEdit, ListView } from "std-widgets.slint";
import { TopicCard } from "components/topic-card.slint";
import { DarkColorPalette, LightColorPalette, ThemeState } from "theme/color-palette.slint";
import { TopicData, LessonData } from "models.slint";
import { LessonsPage } from "pages/lessons-page.slint";
import { NoTopicPage } from "pages/no-topic-page.slint";
import { LineInputDialog } from "dialogs/line-input-dialog.slint";
import { IconButton } from "components/icon-button.slint";
import "../assets/fonts/Inter-Medium.ttf";
import { SettingsPage } from "pages/settings-page.slint";
import { EmptyState } from "pages/empty-state.slint";
import { Button } from "components/button.slint";

export component AppWindow inherits Window {
    title: "Spaced Repitition Organizer";
    icon: @image-url("../assets/app-icon.svg");

    height: 570px;
    width: 1024px;

    default-font-family: "Inter 24pt";
    default-font-weight: 500;

    // Properties
    property <string> topic_name: "";
    in-out property <[TopicData]> topics: [];
    in-out property <string> current_page: "";
    in-out property <string> topic_to_edit: "";
    in-out property <[LessonData]> lessons: [];
    in-out property <string> lesson_to_edit: "";

    // Callbacks
    callback create_topic_requested(string);
    callback delete_topic(string);
    callback rename_topic_requested(topic: string, new: string);
    callback add_lesson(topic: string, lesson: string);
    callback load_lessons_requested(string);
    callback delete_lesson_requested(topic: string, lesson: string);
    callback review_lesson_requested(topic: string, lesson: string, stage: int);
    callback rename_lesson_requested(topic: string, lesson: string, new: string);

    background: ThemeState.isLight ? LightColorPalette.Background : DarkColorPalette.Background;

    // Horizontal layout
    HorizontalLayout {
        // Content control space
        Rectangle {
            width: 250px;

            background: ThemeState.isLight ? LightColorPalette.SideBar : DarkColorPalette.SideBar;
            border-color: ThemeState.isLight ? LightColorPalette.Border : DarkColorPalette.Border;
            border-width: 1px;

            VerticalLayout {
                width: parent.width;
                height: parent.height;

                spacing: 10px;
                padding: 10px;
                Text {
                    vertical-alignment: center;
                    height: 30px;
                
                    text: "Topics";
                    font-size: 20px;

                    color: ThemeState.isLight ? LightColorPalette.Text : DarkColorPalette.Text;
                }

                HorizontalLayout {
                    spacing: 10px;

                    LineEdit {
                        placeholder-text: "New topic...";
                        font-size: 16px;

                        text <=> root.topic_name;

                        accepted() => {
                            if root.topic_name != "" {
                                create_topic_requested(root.topic_name);
                                root.topic_name = "";
                            }
                        }
                    }

                    IconButton {
                        height: 35px;
                        width: 35px;

                        icon: @image-url("../assets/icons/add.svg");
                        icon-size: 20px;

                        enabled: !root.topic_name.is-empty;

                        clicked => {
                            create_topic_requested(root.topic_name);
                            root.topic_name = "";
                        }
                    }
                }

                ListView {
                    for topic[i] in topics: Rectangle {
                        height: 70px;

                        TopicCard {
                            y: 10px;

                            title: root.topics[topics.length - 1 - i].title;
                            lessons: root.topics[topics.length - 1 - i].lessons;
                            due: root.topics[topics.length - 1 - i].due;

                            isSelected: root.current_page == root.topics[topics.length - 1 - i].title;

                            delete_requested => {
                                delete_topic(root.topics[topics.length - 1 - i].title);
                            }

                            edit_requested => {
                                rename-topic-dialog.visible = true;
                                root.topic_to_edit = root.topics[topics.length - 1 - i].title;
                            }

                            selected => {
                                root.current_page = root.topics[topics.length - 1 - i].title;
                                load_lessons_requested(root.current_page)
                            }
                        }
                    }
                }

                Button {
                    text: "Settings";
                    
                    icon: @image-url("../assets/icons/setting.svg");
                    colorize-icon: true;

                    height: 30px;
                    width: 230px;

                    clicked => {
                        root.current_page = "settings";
                    }
                }
            }   
        }   

        // Content space
        if (root.current_page == "" || root.topics.length == 0) : NoTopicPage {

        }

        if (root.current_page == "settings") : SettingsPage {

        }

        if (root.current_page != "" && root.current_page != "settings" && root.topics.length > 0) : LessonsPage {
            topic: root.current_page;
            lessons: root.lessons;

            add_lesson(lesson) => {
                root.add_lesson(root.current_page, lesson);
            }

            load_lessons_requested => {
                root.load_lessons_requested(root.current_page);
            }

            delete_lesson(lesson) => {
                root.delete_lesson_requested(root.current_page, lesson);
            }

            review_lesson(lesson, stage) => {
                root.review_lesson_requested(root.current_page, lesson, stage);
            }

            rename_lesson(lesson) => {
                rename-lesson-dialog.visible = true;
                root.lesson_to_edit = lesson;
            }
        }
    }

    // Popups
    rename-lesson-dialog := LineInputDialog {
        tip: "New lesson name:";

        accepted(new_name) => {
            root.rename_lesson_requested(root.current_page, root.lesson_to_edit, new_name);
            root.lesson_to_edit = "";
        }
    }

    rename-topic-dialog := LineInputDialog {
        tip: "New topic name:";

        accepted(new_name) => {
            root.rename_topic_requested(root.topic_to_edit, new-name);
            root.topic_to_edit = "";
        }
    }
}
