import { Button, LineEdit, ListView } from "std-widgets.slint";
import { TopicCard } from "components/topic-card.slint";
import { DarkColorPalette, LightColorPalette, ThemeState } from "theme/color-palette.slint";
import { TopicData, LessonData } from "models.slint";
import { LessonsPage } from "pages/lessons-page.slint";
import { NoTopicPage } from "pages/no-topic-page.slint";
import { LineInputDialog } from "dialogs/line-input-dialog.slint";

export component AppWindow inherits Window {
    height: 570px;
    width: 1024px;

    // Properties
    property <string> topic_name: "";
    in-out property <[TopicData]> topics: [];
    in-out property <string> currentTopic: "";
    in-out property <[LessonData]> lessons: [];

    // Callbacks
    callback create_topic_requested(string);
    callback delete_topic(string);
    callback add_lesson(topic: string, lesson: string);
    callback load_lessons_requested(string);
    callback delete_lesson_requested(topic: string, lesson: string);
    callback review_lesson_requested(topic: string, lesson: string, stage: int);

    background: ThemeState.isLight ? LightColorPalette.Background : DarkColorPalette.Background;

    // Horizontal layout
    HorizontalLayout {
        // Content control space
        Rectangle {
            width: 250px;

            background: ThemeState.isLight ? LightColorPalette.SideBar : DarkColorPalette.SideBar;
            border-color: ThemeState.isLight ? LightColorPalette.Border : DarkColorPalette.Border;
            border-width: 1px;

            VerticalLayout {
                width: parent.width;
                height: parent.height;

                spacing: 10px;
                padding: 10px;
                Text {
                    vertical-alignment: center;
                    height: 30px;
                
                    text: "Topics";
                    font-size: 20px;

                    color: ThemeState.isLight ? LightColorPalette.Text : DarkColorPalette.Text;
                }

                HorizontalLayout {
                    spacing: 10px;

                    LineEdit {
                        placeholder-text: "New topic...";
                        font-size: 16px;

                        text <=> root.topic_name;

                        accepted() => {
                            if root.topic_name != "" {
                                create_topic_requested(root.topic_name);
                                root.topic_name = "";
                            }
                        }
                    }

                    Button {
                        height: 35px;
                        width: 35px;

                        text: "+";

                        enabled: !root.topic_name.is-empty;

                        clicked => {
                            create_topic_requested(root.topic_name);
                            root.topic_name = "";
                        }
                    }
                }

                ListView {
                    for topic[i] in topics: Rectangle {
                        height: 70px;

                        TopicCard {
                            y: 10px;

                            title: root.topics[topics.length - 1 - i].title;
                            lessons: root.topics[topics.length - 1 - i].lessons;
                            due: root.topics[topics.length - 1 - i].due;

                            isSelected: root.currentTopic == root.topics[topics.length - 1 - i].title;

                            delete_requested => {
                                delete_topic(root.topics[topics.length - 1 - i].title);
                            }

                            selected => {
                                root.currentTopic = root.topics[topics.length - 1 - i].title;
                                load_lessons_requested(root.currentTopic)
                            }
                        }
                    }
                }
            }   
        }   

        // Content space
        if (root.currentTopic == "" || root.topics.length == 0) : NoTopicPage {

        }

        if (root.currentTopic != "" && root.topics.length > 0) : LessonsPage {
            topic: root.currentTopic;
            lessons: root.lessons;

            add_lesson(lesson) => {
                root.add_lesson(root.currentTopic, lesson);
            }

            load_lessons_requested => {
                root.load_lessons_requested(root.currentTopic);
            }

            delete_lesson(lesson) => {
                root.delete_lesson_requested(root.currentTopic, lesson);
            }

            review_lesson(lesson, stage) => {
                root.review_lesson_requested(root.currentTopic, lesson, stage);
            }

            rename_lesson(lesson) => {
                rename-dialog.visible = true;
            }
        }
    }

    // Popups
    rename-dialog := LineInputDialog {
        tip: "New lesson name:";
    }
}
