import { Button, LineEdit } from "std-widgets.slint";
import { TopicCard } from "components/topic-card.slint";
import { DarkColorPalette, LightColorPalette, ThemeState } from "theme/color-palette.slint";

export component AppWindow inherits Window {
    height: 570px;
    width: 1024px;

    // Callbacks
    callback create_topic_requested(string);

    // Properties
    property <string> topic_name: "";

    background: ThemeState.isLight ? LightColorPalette.Background : DarkColorPalette.Background;

    // Horizontal layout
    HorizontalLayout {
        // Content control space
            Rectangle {
                width: 250px;

                background: ThemeState.isLight ? LightColorPalette.SideBar : DarkColorPalette.SideBar;
                border-color: ThemeState.isLight ? LightColorPalette.Border : DarkColorPalette.Border;
                border-width: 1px;

                VerticalLayout {
                width: parent.width;
                height: parent.height;

                spacing: 10px;
                padding: 10px;
                Text {
                    vertical-alignment: center;
                    height: 30px;
                
                    text: "Topics";
                    font-size: 20px;

                    color: ThemeState.isLight ? LightColorPalette.Text : DarkColorPalette.Text;
                }
                
                HorizontalLayout {
                    spacing: 10px;

                    LineEdit {
                        placeholder-text: "New topic...";
                        font-size: 16px;

                        text <=> root.topic_name;
                    }
                    
                    Button {
                        height: 35px;
                        width: 35px;

                        text: "+";

                        enabled: !root.topic_name.is-empty;

                        clicked => {
                            create_topic_requested(root.topic_name);
                            root.topic_name = "";
                        }
                    }
                }

                TopicCard {
                    title: "arabic grammar";
                    lessons: 6;
                    due: 1;
                }

                TopicCard {
                    title: "physics";
                    lessons: 4;
                    due: 2;
                }
            }
        }

        // Content space
        VerticalLayout {
            HorizontalLayout {
                padding: 10px;
                spacing: 10px;

                Text {
                    vertical-alignment: center;
                    height: 30px;

                    text: "arabic grammar";
                    font-size: 20px;

                    color: ThemeState.isLight ? LightColorPalette.Text : DarkColorPalette.Text;
                }

                LineEdit {
                    placeholder-text: "New lesson name..";
                    font-size: 16px;
                }

                Button {
                    text: "+ Add lesson";
                }
            }
        }
    }
}
